name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run specific tests by spec
        default: cypress/e2e/*        

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Enable Corepack
        run: corepack enable

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:    
          install-command: yarn install --immutable
          pre-run: npx cypress verify || npx cypress install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

