name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run specific tests by spec
        default: cypress/e2e/*        

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies and Cypress
        run: |
          yarn install --immutable
          npx cypress install
          npx cypress verify

      - name: Clear Cypress cache (if needed)
        run: npx cypress cache clear || true

      - name: Verify Cypress cache
        run: npx cypress cache list

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.5.0
        with:    
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

