name: Cypress Tests Report

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run Cypress tests
        default: yarn cypress run        

jobs:
  cypress-multibrowser-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [electron, chrome, firefox]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      - name: Setup Corepack & Use Correct Yarn Version
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Create Necessary Directories
        run: mkdir -p cypress/reports/mochawesome cypress/reports/junit cypress/videos cypress/screenshots

      - name: Run E2E Tests on ${{ matrix.browser }}
        run: yarn cypress run --browser ${{ matrix.browser }}

      - name: Upload Cypress Reports
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports-${{ matrix.browser }}
          path: cypress/reports
          if-no-files-found: ignore

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos
          if-no-files-found: ignore

      - name: Upload Cypress Screenshots (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          if-no-files-found: ignore

  deploy-report:
    needs: cypress-multibrowser-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4.2.2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Download Cypress Reports
        uses: actions/download-artifact@v4
        with:
          name: cypress-reports-electron
          path: report/electron

      - uses: actions/download-artifact@v4
        with:
          name: cypress-reports-chrome
          path: report/chrome

      - uses: actions/download-artifact@v4
        with:
          name: cypress-reports-firefox
          path: report/firefox

      - name: Criar um arquivo index.html para redirecionamento
        run: |
          echo '<meta http-equiv="refresh" content="0; url=./chrome/index.html">' > report/index.html

      - name: Publish Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report
          force_orphan: true
