name: Cypress Tests Report

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run Cypress tests
        default: yarn cypress run        

jobs:
  cypress-multibrowser-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [electron, chrome, firefox]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      - name: Enable Corepack
        run: corepack enable

      - name: Verify Yarn Version
        run: yarn --version

      - name: Setup Node.js Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/yarn
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Set Cypress Cache Folder
        run: echo "CYPRESS_CACHE_FOLDER=~/.cache/Cypress" >> $GITHUB_ENV

      - name: Restore Cypress Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Create Necessary Directories
        run: mkdir -p cypress/reports/mochawesome cypress/reports/junit cypress/videos cypress/screenshots

      - name: Run E2E Tests on ${{ matrix.browser }}
        run: yarn cypress run --browser ${{ matrix.browser }}

      - name: Upload Cypress Reports
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports
          if-no-files-found: ignore

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: Upload Cypress Screenshots (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

