name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by Cypress command line
        default: yarn cypress run        

jobs:
  cypress-multibrowser-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [electron, chrome, firefox]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      - name: Enable Corepack
        run: corepack enable

      - name: Verify Yarn Version
        run: yarn --version

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Ensure Cypress Reporters are Installed
        run: yarn add cypress-mochawesome-reporter cypress-multi-reporters mocha-junit-reporter --dev

      - name: Create Report Directory
        run: mkdir -p cypress/reports/mochawesome cypress/reports/junit

      - name: Run E2E Tests on ${{ matrix.browser }}
        run: yarn cypress run --browser ${{ matrix.browser }}

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-mochawesome-report
          path: cypress/reports/mochawesome

      - name: Upload JUnit Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-junit-report
          path: cypress/reports/junit
